### PR TITLE
Fix uninformative error messages

### LINKED ISSUE #13: Uninformative error messages on wrong timespan
# Problem
The when running sample code:
https://github.com/glenn-m/promR/blob/13faf82a09e54d1b6baee00714f907f11598d159/README.Rmd#L32-L34
the query would return data frame with 0 rows:
```r
metrics_current <- prom$query(query = "go_goroutines", 
                              time = format(Sys.time(),  "%Y-%m-%dT%H:%M:%SZ"))
# Error in format_metrics_current_data(metrics) : 
#  Assertion on 'x' failed: Must have at least 1 rows, but has 0 rows.
metrics_current <- prom$query(query = "go_goroutines", 
                             time = format(Sys.time() - 10,  "%Y-%m-%dT%H:%M:%SZ"))
 # Error in format_metrics_current_data(metrics) : 
 #  Assertion on 'x' failed: Must have at least 1 rows, but has 0 rows.
```
for:

```r
Sys.time()
# [1] "2019-04-01 07:22:00 BST"
```

the data would be produced for `Sys.time() - 3600`

```r
metrics_current <- prom$query(query = "go_goroutines", 
                               time = format(Sys.time() - 3600,  "%Y-%m-%dT%H:%M:%SZ"))
```

It's unclear whether:
 * there is no data for the period corresponding to `07:22` but there is for an hour earlier (?) `Sys.time() - 3600` 
 * the connection failed
 * query failed

# Suggested resolution

## For internet connection

If possible to solve through #11 if not consider running `curl::has_internet()` before query, return stop
```r
if (!curl::has_internet()) stop("This machine is not connected to the Internet :)")
```

## For query

Shall return something like (?):

> The query completed but returned no data....

---
Potentially related to #11

### PR DESCRIPTION
**Pull request by konradzdeb**
Probably not the most sophisticated solution there could be but, IMHO, it can close #13 for now as a more informative error message is returned when the produced data frame is empty.

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -26,6 +26,26 @@ response_check <- function(response) {
...
+metrics_check <- function(metric) {
+  withCallingHandlers(
+    expr =
+      checkmate::assert_data_frame(
+        x = metric,
+        min.rows = 1,
+        min.cols = 2
+      ),
+    error = function(e) {
+      stop("Returned metrics object is empty:", e, call. = FALSE)
```
Comment (glenn-m) [inline R/utils.R]: Being pedantic but can we add in a space after the colon, like so:

```R
stop("Returned metrics object is empty: ", e, call. = FALSE)
```

**Review by glenn-m — CHANGES_REQUESTED** [review]

**Comment by konradzdeb** [comment]
Well spotted, I’ll fix send an update 

--
Konrad

File: R/utils.R (hunk 1 above)
Comment (konradzdeb) [reply R/utils.R]: Fixed in 1a4dbd92795dc3b8cacb7c66ff4721408e767c33

**Review by glenn-m — APPROVED** [review]
